name: make-system-user
version: '6'
summary: Make a system user file for auto import
description: Make an auto-import.assert file
  containing required assertions to create a system user
  signed by your registered key

grade: stable
confinement: classic 

apps:
    make-system-user:
        command: bin/make_system_user

parts:
    env:
        plugin: python
        source: src
        python-packages:
            - snapcraft
            - PyYAML
            - click
        override-build: |
            snapcraftctl build
            cp run.sh $SNAPCRAFT_PART_INSTALL/bin/run.sh
            cp make_system_user.py $SNAPCRAFT_PART_INSTALL/bin/make_system_user.py