name: make-system-user
version: '12'
summary: Make a system user file for auto import
description: Make an auto-import.assert file
  containing required assertions to create a system user
  signed by your registered key

grade: stable
confinement: classic 
base: core20

apps:
    make-system-user:
        command: bin/launch.sh
        environment: 
            PYTHONPATH: $SNAP/lib/python3.8/site-packages/

parts:
    make-system-user:
        plugin: python
        source: src
        python-packages: [ argparse, requests, simplejson, pymacaroons, pyxdg ]
        stage-packages: [ python3-venv ]
        #override-stage: |
        #    snapcraftctl stage
        #    chmod a+x $SNAPCRAFT_STAGE/lib/python3.8/site-packages/make_system_user/__main__.py
    bin:
      source: launchers
      plugin: dump

