name: make-system-user
version: '7'
summary: Make a system user file for auto import
description: Make an auto-import.assert file
  containing required assertions to create a system user
  signed by your registered key

grade: stable
confinement: classic 

apps:
    make-system-user:
        command: bin/make_system_user

parts:
    # this part is necessary because snapcraft doesn't correctly migrate the
    # dependencies for the snapcraft package into the final snap, so we 
    # have to manually add all the dependencies
    snapcraft-pip:
        plugin: nil
        source: https://github.com/snapcore/snapcraft.git
        source-tag: "2.42"
        source-depth: 1
        stage-packages: 
        - libc6
        - libapt-pkg-dev
        - libsodium-dev
        override-build: |
            pip3 install -r requirements.txt -t $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages --ignore-installed
    env:
        after: [snapcraft-pip]
        plugin: python
        python-version: python3
        source: .
        stage-packages: 
        - libc6
