name: make-system-user
version: '12'
summary: Make a system user file for auto import
description: Make an auto-import.assert file
  containing required assertions to create a system user
  signed by your registered key

grade: stable
confinement: classic 
base: core20

apps:
    make-system-user:
        command: bin/make_system_user

parts:
    env:
        plugin: python
        source: .
        #        override-build: |
        #    snapcraftctl build
        #    cp $SNAPCRAFT_PROJECT_DIR/mydirspy $SNAPCRAFT_PART_INSTALL/lib/python3.6/site-packages/snapcraft/internal/dirs.py
